import { prisma } from "./db";

async function main() {
  await prisma.set.deleteMany({});
  await prisma.exerciseLog.deleteMany({});
  await prisma.exerciseLog.deleteMany({});
  await prisma.exercise.deleteMany({});
  await prisma.exercise.createMany({
    data: [
      { name: "Incline Barbell Bench Press", tags: ["Chest", "Strength"] },
      { name: "Decline Barbell Bench Press", tags: ["Chest", "Strength"] },
      { name: "Barbell Bench Press", tags: ["Chest", "Strength"] },
      { name: "Guillotine Press", tags: ["Chest", "Strength"] },
      { name: "Barbell Floor Press", tags: ["Chest", "Power"] },
      { name: "Spoto Press", tags: ["Chest", "Triceps"] },
      { name: "Reverse-Grip Bench Press", tags: ["Chest", "Triceps"] },
      { name: "Pin Press", tags: ["Chest", "Strength"] },
      { name: "Smith Machine Bench Press", tags: ["Chest", "Machine"] },
      { name: "Dumbbell Bench Press", tags: ["Chest", "Dumbbell"] },
      { name: "Incline Dumbbell Bench Press", tags: ["Chest", "Upper Chest"] },
      { name: "Decline Dumbbell Bench Press", tags: ["Chest", "Lower Chest"] },
      { name: "Dumbbell Fly", tags: ["Chest", "Isolation"] },
      { name: "Incline Dumbbell Fly", tags: ["Chest", "Upper Chest"] },
      { name: "Decline Dumbbell Fly", tags: ["Chest", "Lower Chest"] },
      { name: "Dumbbell Pullover", tags: ["Chest", "Lats"] },
      { name: "Dumbbell Squeeze Press", tags: ["Chest", "Strength"] },
      { name: "Dumbbell Floor Press", tags: ["Chest", "Power"] },
      { name: "Machine Chest Press", tags: ["Chest", "Machine"] },
      { name: "Incline Machine Chest Press", tags: ["Chest", "Upper Chest"] },
      { name: "Decline Machine Chest Press", tags: ["Chest", "Lower Chest"] },
      { name: "Pec Deck Machine", tags: ["Chest", "Isolation"] },
      { name: "Seated Chest Fly Machine", tags: ["Chest", "Machine"] },
      { name: "Plate-Loaded Chest Press", tags: ["Chest", "Strength"] },
      { name: "Hammer Strength Chest Press", tags: ["Chest", "Strength"] },
      { name: "Hammer Strength Incline Press", tags: ["Chest", "Upper Chest"] },
      { name: "Assisted Dips (Chest Focus)", tags: ["Chest", "Bodyweight"] },
      { name: "Smith Machine Incline Press", tags: ["Chest", "Machine"] },
      { name: "Cable Crossover", tags: ["Chest", "Cable"] },
      { name: "Low-to-High Cable Fly", tags: ["Chest", "Cable"] },
      { name: "High-to-Low Cable Fly", tags: ["Chest", "Cable"] },
      { name: "Standing Cable Chest Press", tags: ["Chest", "Cable"] },
      { name: "Cable Squeeze Press", tags: ["Chest", "Cable"] },
      { name: "Single-Arm Cable Press", tags: ["Chest", "Cable"] },
      { name: "Cable Pullover", tags: ["Chest", "Back"] },
      { name: "Lying Cable Fly", tags: ["Chest", "Cable"] },
      { name: "Cable Chest Dips", tags: ["Chest", "Bodyweight"] },
      { name: "Cable Iron Cross", tags: ["Chest", "Cable"] },
      { name: "Push-Ups", tags: ["Chest", "Bodyweight"] },
      { name: "Decline Push-Ups", tags: ["Chest", "Bodyweight"] },
      { name: "Incline Push-Ups", tags: ["Chest", "Bodyweight"] },
      { name: "Weighted Push-Ups", tags: ["Chest", "Strength"] },
      { name: "Archer Push-Ups", tags: ["Chest", "Bodyweight"] },
      { name: "Plyometric (Clap) Push-Ups", tags: ["Chest", "Explosive"] },
      { name: "Spiderman Push-Ups", tags: ["Chest", "Core"] },
      { name: "Ring Push-Ups", tags: ["Chest", "Stability"] },
      { name: "Medicine Ball Push-Ups", tags: ["Chest", "Stability"] },
      { name: "One-Arm Push-Ups", tags: ["Chest", "Strength"] },
      { name: "Barbell Row", tags: ["Back", "Strength"] },
      { name: "Pendlay Row", tags: ["Back", "Strength"] },
      { name: "Dumbbell Row", tags: ["Back", "Strength"] },
      { name: "Single-Arm Dumbbell Row", tags: ["Back", "Isolation"] },
      { name: "T-Bar Row", tags: ["Back", "Strength"] },
      { name: "Seated Cable Row", tags: ["Back", "Cable"] },
      { name: "Wide-Grip Lat Pulldown", tags: ["Back", "Lats"] },
      { name: "Close-Grip Lat Pulldown", tags: ["Back", "Lats"] },
      { name: "Reverse-Grip Lat Pulldown", tags: ["Back", "Lats"] },
      { name: "Neutral-Grip Lat Pulldown", tags: ["Back", "Lats"] },
      { name: "Pull-Ups", tags: ["Back", "Bodyweight"] },
      { name: "Weighted Pull-Ups", tags: ["Back", "Strength"] },
      { name: "Chin-Ups", tags: ["Back", "Biceps"] },
      { name: "Wide-Grip Pull-Ups", tags: ["Back", "Lats"] },
      { name: "Close-Grip Pull-Ups", tags: ["Back", "Biceps"] },
      { name: "Deadlifts", tags: ["Full Body", "Strength"] },
      { name: "Sumo Deadlifts", tags: ["Legs", "Glutes"] },
      { name: "Romanian Deadlifts", tags: ["Hamstrings", "Strength"] },
      { name: "Snatch-Grip Deadlift", tags: ["Back", "Posterior Chain"] },
      { name: "Rack Pulls", tags: ["Back", "Strength"] },
      { name: "Seal Rows", tags: ["Back", "Isolation"] },
      { name: "Reverse Fly", tags: ["Shoulders", "Rear Delts"] },
      { name: "Bent-Over Reverse Fly", tags: ["Shoulders", "Rear Delts"] },
      { name: "Straight-Arm Pulldown", tags: ["Back", "Lats"] },
      { name: "Cable Row", tags: ["Back", "Cable"] },
      { name: "One-Arm Cable Row", tags: ["Back", "Unilateral"] },
      { name: "Meadows Row", tags: ["Back", "Strength"] },
      { name: "Kroc Rows", tags: ["Back", "Strength"] },
      { name: "Landmine Row", tags: ["Back", "Strength"] },
      { name: "Smith Machine Row", tags: ["Back", "Machine"] },
      { name: "Machine Lat Pulldown", tags: ["Back", "Machine"] },
      { name: "Chest-Supported Row", tags: ["Back", "Isolation"] },
      { name: "Machine Row", tags: ["Back", "Machine"] },
      { name: "Hammer Strength Row", tags: ["Back", "Strength"] },
      { name: "Dead Hang", tags: ["Grip", "Endurance"] },
      { name: "Inverted Rows", tags: ["Back", "Bodyweight"] },
      { name: "Towel Pull-Ups", tags: ["Back", "Grip"] },
      { name: "Archer Pull-Ups", tags: ["Back", "Strength"] },
      { name: "Rope Climb", tags: ["Back", "Grip"] },
      { name: "Reverse Shrugs", tags: ["Traps", "Strength"] },
      { name: "Superman Hold", tags: ["Core", "Endurance"] },
      { name: "Reverse Hyperextensions", tags: ["Lower Back", "Glutes"] },
      { name: "Farmers Carry", tags: ["Grip", "Strength"] },
      { name: "Barbell Curl", tags: ["Biceps", "Strength"] },
      { name: "Dumbbell Curl", tags: ["Biceps", "Isolation"] },
      { name: "Hammer Curl", tags: ["Biceps", "Forearms"] },
      { name: "Concentration Curl", tags: ["Biceps", "Isolation"] },
      { name: "Preacher Curl", tags: ["Biceps", "Isolation"] },
      { name: "Cable Curl", tags: ["Biceps", "Cable"] },
      { name: "Reverse Curl", tags: ["Biceps", "Forearms"] },
      { name: "Zottman Curl", tags: ["Biceps", "Forearms"] },
      { name: "Chin-Up Bicep Curl", tags: ["Biceps", "Bodyweight"] },
      { name: "Spider Curl", tags: ["Biceps", "Isolation"] },
      { name: "EZ Bar Curl", tags: ["Biceps", "Strength"] },
      { name: "Incline Dumbbell Curl", tags: ["Biceps", "Strength"] },
      { name: "Seated Dumbbell Curl", tags: ["Biceps", "Isolation"] },
      { name: "Drag Curl", tags: ["Biceps", "Strength"] },
      { name: "Bayesian Curl", tags: ["Biceps", "Cable"] },
      { name: "Cable Rope Curl", tags: ["Biceps", "Cable"] },
      { name: "Single-Arm Cable Curl", tags: ["Biceps", "Unilateral"] },
      { name: "Barbell 21s Curl", tags: ["Biceps", "Strength"] },
      { name: "Plate Curl", tags: ["Biceps", "Grip"] },
      { name: "Cross-Body Hammer Curl", tags: ["Biceps", "Forearms"] },
      { name: "Dumbbell Zottman Curl", tags: ["Biceps", "Forearms"] },
      { name: "Alternating Dumbbell Curl", tags: ["Biceps", "Isolation"] },
      { name: "Machine Bicep Curl", tags: ["Biceps", "Machine"] },
      { name: "Isometric Bicep Hold", tags: ["Biceps", "Endurance"] },
      { name: "Barbell Cheat Curl", tags: ["Biceps", "Strength"] },
      { name: "Dumbbell Wrist Curl", tags: ["Forearms", "Strength"] },
      { name: "Skull Crushers", tags: ["Triceps", "Strength"] },
      { name: "Close-Grip Bench Press", tags: ["Triceps", "Strength"] },
      { name: "Overhead Triceps Extension", tags: ["Triceps", "Isolation"] },
      { name: "Triceps Dips", tags: ["Triceps", "Bodyweight"] },
      { name: "Triceps Rope Pushdown", tags: ["Triceps", "Cable"] },
      { name: "French Press", tags: ["Triceps", "Strength"] },
      { name: "Single-Arm Triceps Extension", tags: ["Triceps", "Unilateral"] },
      { name: "Diamond Push-Ups", tags: ["Triceps", "Bodyweight"] },
      { name: "Dumbbell Kickbacks", tags: ["Triceps", "Isolation"] },
      { name: "EZ Bar Skull Crushers", tags: ["Triceps", "Strength"] },
      { name: "Cable Overhead Triceps Extension", tags: ["Triceps", "Cable"] },
      { name: "Reverse-Grip Triceps Pushdown", tags: ["Triceps", "Cable"] },
      {
        name: "Seated Dumbbell Triceps Extension",
        tags: ["Triceps", "Strength"],
      },
      { name: "Dumbbell Tate Press", tags: ["Triceps", "Strength"] },
      { name: "Dips Machine", tags: ["Triceps", "Machine"] },
      { name: "Barbell JM Press", tags: ["Triceps", "Strength"] },
      { name: "Ring Dips", tags: ["Triceps", "Bodyweight"] },
      {
        name: "Bodyweight Triceps Extensions",
        tags: ["Triceps", "Bodyweight"],
      },
      {
        name: "Cable One-Arm Triceps Pushdown",
        tags: ["Triceps", "Unilateral"],
      },
      { name: "Machine Triceps Dips", tags: ["Triceps", "Machine"] },
      { name: "Parallel Bar Dips", tags: ["Triceps", "Bodyweight"] },
      { name: "Weighted Dips", tags: ["Triceps", "Strength"] },
      {
        name: "Resistance Band Triceps Extension",
        tags: ["Triceps", "Resistance"],
      },
      { name: "Isometric Triceps Hold", tags: ["Triceps", "Endurance"] },
      { name: "Decline Close-Grip Push-Ups", tags: ["Triceps", "Bodyweight"] },
      { name: "Barbell Squat", tags: ["Legs", "Strength"] },
      { name: "Front Squat", tags: ["Legs", "Quads"] },
      { name: "Bulgarian Split Squat", tags: ["Legs", "Unilateral"] },
      { name: "Hack Squat", tags: ["Legs", "Machine"] },
      { name: "Goblet Squat", tags: ["Legs", "Strength"] },
      { name: "Overhead Squat", tags: ["Legs", "Stability"] },
      { name: "Box Squat", tags: ["Legs", "Power"] },
      { name: "Zercher Squat", tags: ["Legs", "Strength"] },
      { name: "Sissy Squat", tags: ["Legs", "Bodyweight"] },
      { name: "Anderson Squat", tags: ["Legs", "Strength"] },
      { name: "Leg Press", tags: ["Legs", "Strength"] },
      { name: "Single-Leg Leg Press", tags: ["Legs", "Unilateral"] },
      { name: "Step-Ups", tags: ["Legs", "Unilateral"] },
      { name: "Walking Lunges", tags: ["Legs", "Endurance"] },
      { name: "Reverse Lunges", tags: ["Legs", "Glutes"] },
      { name: "Side Lunges", tags: ["Legs", "Mobility"] },
      { name: "Curtsy Lunges", tags: ["Legs", "Glutes"] },
      { name: "Jump Squats", tags: ["Legs", "Explosive"] },
      { name: "Pistol Squats", tags: ["Legs", "Balance"] },
      { name: "Wall Sit", tags: ["Legs", "Endurance"] },
      { name: "Romanian Deadlift", tags: ["Hamstrings", "Strength"] },
      { name: "Stiff-Leg Deadlift", tags: ["Hamstrings", "Strength"] },
      { name: "Sumo Deadlift", tags: ["Legs", "Glutes"] },
      { name: "Trap Bar Deadlift", tags: ["Legs", "Strength"] },
      { name: "Jefferson Deadlift", tags: ["Legs", "Core"] },
      { name: "Nordic Hamstring Curl", tags: ["Hamstrings", "Bodyweight"] },
      { name: "Glute Ham Raise", tags: ["Hamstrings", "Glutes"] },
      { name: "Good Mornings", tags: ["Lower Back", "Hamstrings"] },
      { name: "Seated Leg Curl", tags: ["Hamstrings", "Machine"] },
      { name: "Lying Leg Curl", tags: ["Hamstrings", "Machine"] },
      { name: "Standing Leg Curl", tags: ["Hamstrings", "Machine"] },
      { name: "Cable Kickbacks", tags: ["Glutes", "Cable"] },
      { name: "Hip Thrusts", tags: ["Glutes", "Strength"] },
      { name: "Glute Bridges", tags: ["Glutes", "Bodyweight"] },
      { name: "Donkey Kicks", tags: ["Glutes", "Bodyweight"] },
      { name: "Fire Hydrants", tags: ["Glutes", "Mobility"] },
      { name: "Leg Extensions", tags: ["Quads", "Machine"] },
      { name: "Seated Calf Raise", tags: ["Calves", "Machine"] },
      { name: "Standing Calf Raise", tags: ["Calves", "Strength"] },
      { name: "Donkey Calf Raise", tags: ["Calves", "Strength"] },
      { name: "Single-Leg Calf Raise", tags: ["Calves", "Unilateral"] },
      { name: "Farmer’s Walk on Toes", tags: ["Calves", "Endurance"] },
      { name: "Tire Flips", tags: ["Full Body", "Power"] },
      { name: "Atlas Stones", tags: ["Full Body", "Strength"] },
      { name: "Box Jumps", tags: ["Legs", "Explosive"] },
      { name: "Barbell Overhead Press", tags: ["Shoulders", "Strength"] },
      {
        name: "Seated Barbell Overhead Press",
        tags: ["Shoulders", "Strength"],
      },
      { name: "Dumbbell Shoulder Press", tags: ["Shoulders", "Strength"] },
      {
        name: "Seated Dumbbell Shoulder Press",
        tags: ["Shoulders", "Strength"],
      },
      { name: "Arnold Press", tags: ["Shoulders", "Mobility"] },
      { name: "Machine Shoulder Press", tags: ["Shoulders", "Machine"] },
      { name: "Smith Machine Shoulder Press", tags: ["Shoulders", "Machine"] },
      { name: "Push Press", tags: ["Shoulders", "Explosive"] },
      { name: "Z-Press", tags: ["Shoulders", "Core"] },
      { name: "Single-Arm Dumbbell Press", tags: ["Shoulders", "Unilateral"] },
      { name: "Single-Arm Landmine Press", tags: ["Shoulders", "Unilateral"] },
      { name: "Standing Military Press", tags: ["Shoulders", "Strength"] },
      { name: "Handstand Push-Ups", tags: ["Shoulders", "Bodyweight"] },
      { name: "Partial Overhead Press", tags: ["Shoulders", "Strength"] },
      { name: "Bradford Press", tags: ["Shoulders", "Mobility"] },
      { name: "Behind-the-Neck Press", tags: ["Shoulders", "Strength"] },
      { name: "Barbell Front Raise", tags: ["Shoulders", "Strength"] },
      { name: "Dumbbell Front Raise", tags: ["Shoulders", "Isolation"] },
      { name: "Plate Front Raise", tags: ["Shoulders", "Strength"] },
      { name: "Cable Front Raise", tags: ["Shoulders", "Cable"] },
      { name: "Lateral Raises", tags: ["Shoulders", "Isolation"] },
      { name: "Seated Lateral Raises", tags: ["Shoulders", "Isolation"] },
      { name: "Cable Lateral Raise", tags: ["Shoulders", "Cable"] },
      { name: "Machine Lateral Raise", tags: ["Shoulders", "Machine"] },
      { name: "Lean-Away Lateral Raise", tags: ["Shoulders", "Isolation"] },
      { name: "Bent-Over Lateral Raises", tags: ["Shoulders", "Rear Delts"] },
      { name: "Cable Reverse Fly", tags: ["Shoulders", "Cable"] },
      { name: "Face Pulls", tags: ["Shoulders", "Rear Delts"] },
      { name: "Upright Rows", tags: ["Shoulders", "Traps"] },
      { name: "Dumbbell Upright Rows", tags: ["Shoulders", "Traps"] },
      { name: "Trap Bar Shrugs", tags: ["Traps", "Strength"] },
      { name: "Dumbbell Shrugs", tags: ["Traps", "Strength"] },
      { name: "Barbell Shrugs", tags: ["Traps", "Strength"] },
      { name: "Cable Shrugs", tags: ["Traps", "Cable"] },
      { name: "Overhead Shrugs", tags: ["Shoulders", "Traps"] },
      { name: "Y-T-W Raises", tags: ["Shoulders", "Mobility"] },
      { name: "Scapular Pull-Ups", tags: ["Back", "Stability"] },
      { name: "Scapular Push-Ups", tags: ["Chest", "Stability"] },
      { name: "Cuban Press", tags: ["Shoulders", "Mobility"] },
      { name: "Prone Rear Delt Raise", tags: ["Shoulders", "Rear Delts"] },
      { name: "Reverse Pec Deck Fly", tags: ["Shoulders", "Machine"] },
      { name: "Dumbbell External Rotations", tags: ["Shoulders", "Stability"] },
      { name: "Cable External Rotations", tags: ["Shoulders", "Stability"] },
      { name: "Dumbbell Around-the-World", tags: ["Shoulders", "Mobility"] },
      { name: "Dead Hang for Shoulders", tags: ["Grip", "Endurance"] },
      { name: "Front Lever Hold", tags: ["Core", "Strength"] },
      { name: "Incline Dumbbell Raise", tags: ["Shoulders", "Strength"] },
      { name: "Jump Rope", tags: ["Cardio", "Endurance"] },
      { name: "Double Unders", tags: ["Cardio", "Agility"] },
      { name: "Running (Treadmill)", tags: ["Cardio", "Endurance"] },
      { name: "Outdoor Running", tags: ["Cardio", "Endurance"] },
      { name: "Sprint Intervals", tags: ["Cardio", "Explosive"] },
      { name: "Hill Sprints", tags: ["Cardio", "Strength"] },
      { name: "Rowing Machine", tags: ["Cardio", "Back"] },
      { name: "Cycling (Stationary Bike)", tags: ["Cardio", "Legs"] },
      { name: "Outdoor Cycling", tags: ["Cardio", "Legs"] },
      { name: "Assault Bike", tags: ["Cardio", "Full Body"] },
      { name: "Ski Erg", tags: ["Cardio", "Full Body"] },
      { name: "Elliptical Trainer", tags: ["Cardio", "Full Body"] },
      { name: "Stair Climber", tags: ["Cardio", "Legs"] },
      { name: "Battle Ropes", tags: ["Cardio", "Strength"] },
      { name: "Jumping Jacks", tags: ["Cardio", "Full Body"] },
      { name: "High Knees", tags: ["Cardio", "Legs"] },
      { name: "Butt Kicks", tags: ["Cardio", "Legs"] },
      { name: "Lateral Shuffles", tags: ["Cardio", "Agility"] },
      { name: "Burpees", tags: ["Cardio", "Full Body"] },
      { name: "Mountain Climbers", tags: ["Cardio", "Core"] },
      { name: "Broad Jumps", tags: ["Cardio", "Explosive"] },
      { name: "Agility Ladder Drills", tags: ["Cardio", "Agility"] },
      { name: "Speed Skaters", tags: ["Cardio", "Balance"] },
      { name: "Bear Crawls", tags: ["Full Body", "Core"] },
      { name: "Crab Walks", tags: ["Full Body", "Mobility"] },
      { name: "Farmer's Carry", tags: ["Grip", "Strength"] },
      { name: "Sled Push", tags: ["Legs", "Strength"] },
      { name: "Sled Drag", tags: ["Legs", "Strength"] },
      { name: "Yoke Carry", tags: ["Full Body", "Strength"] },
      { name: "Medicine Ball Slams", tags: ["Core", "Power"] },
      { name: "Kettlebell Swings", tags: ["Full Body", "Strength"] },
      { name: "Jump Lunges", tags: ["Legs", "Explosive"] },
      { name: "Shadow Boxing", tags: ["Cardio", "Upper Body"] },
      { name: "Kickboxing Drills", tags: ["Cardio", "Agility"] },
      { name: "Swimming", tags: ["Cardio", "Full Body"] },
      { name: "Rowing (Outdoor)", tags: ["Cardio", "Back"] },
      { name: "Hiking", tags: ["Cardio", "Endurance"] },
      { name: "Jumping Split Squats", tags: ["Legs", "Explosive"] },
      { name: "Speed Rope Skipping", tags: ["Cardio", "Agility"] },
      { name: "Medicine Ball Wall Throws", tags: ["Full Body", "Power"] },
      { name: "Sledgehammer Swings", tags: ["Full Body", "Power"] },
      { name: "Frog Jumps", tags: ["Legs", "Explosive"] },
      { name: "Lateral Hops", tags: ["Legs", "Agility"] },
      { name: "Overhead Plate Carry", tags: ["Shoulders", "Strength"] },
      { name: "Sprint Ladder Drills", tags: ["Cardio", "Speed"] },
      { name: "Side-to-Side Hops", tags: ["Cardio", "Agility"] },
      { name: "Plank", tags: ["Core", "Endurance"] },
      { name: "Side Plank", tags: ["Core", "Endurance"] },
      { name: "Hanging Leg Raises", tags: ["Core", "Strength"] },
      { name: "Ab Rollouts", tags: ["Core", "Strength"] },
      { name: "Cable Crunches", tags: ["Core", "Strength"] },
      { name: "Bicycle Crunches", tags: ["Core", "Obliques"] },
      { name: "Russian Twists", tags: ["Core", "Obliques"] },
      { name: "V-Ups", tags: ["Core", "Strength"] },
      { name: "Flutter Kicks", tags: ["Core", "Endurance"] },
      { name: "Toes to Bar", tags: ["Core", "Strength"] },
      { name: "Woodchopper", tags: ["Core", "Rotation"] },
      { name: "Dragon Flags", tags: ["Core", "Strength"] },
      { name: "Hollow Body Hold", tags: ["Core", "Endurance"] },
      { name: "Sit-Ups", tags: ["Core", "Strength"] },
      { name: "Reverse Crunches", tags: ["Core", "Lower Abs"] },
      { name: "Dead Bug", tags: ["Core", "Stability"] },
      { name: "Lying Leg Raises", tags: ["Core", "Lower Abs"] },
      { name: "Standing Oblique Crunches", tags: ["Core", "Obliques"] },
      { name: "Cable Side Bends", tags: ["Core", "Obliques"] },
      { name: "Hanging Knee Raises", tags: ["Core", "Lower Abs"] },
      { name: "Windshield Wipers", tags: ["Core", "Obliques"] },
      { name: "Swiss Ball Rollouts", tags: ["Core", "Stability"] },
      { name: "Jackknife Sit-Ups", tags: ["Core", "Strength"] },
      { name: "Seated Knee Tucks", tags: ["Core", "Lower Abs"] },
      { name: "Elevated Plank", tags: ["Core", "Endurance"] },
      { name: "Weighted Russian Twists", tags: ["Core", "Obliques"] },
      { name: "Kneeling Ab Wheel Rollouts", tags: ["Core", "Strength"] },
      { name: "Standing Landmine Twists", tags: ["Core", "Rotation"] },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
